### ISSUE TITLE
central file for client configs for dynamic host url

### ISSUE THREAD

**Issue by esteban-gs** [Nonprofit-Exchange-Hub/web-app#106]
We need a central place to dynamically get the host's url. For example, when dockerizing the entire app, the client JS needs to know the full url of the host that is serving it.

Also it can hold all other app constants that make sense.

**Comment by jd2rogers2** [comment]
nice! good add @esteban-gs 
i think this one will be made easier after [monorepo-ize](https://github.com/Nonprofit-Exchange-Hub/web-app/issues/100)
