### ISSUE TITLE
interrupt page refresh or page exit if form is not blank

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#118]
a user fills out a form, then tries to leave without submitting
we want to interrupt this and check that they are doing so intentionally

i'm not sure how to do this TBH so research is required here

**Comment by paaaarv** [comment]
i'd like to pick this ticket up! just a thought though -- could a function that maps through state to see if anything doesn't equal " " before leaving? and then can pop up an alert?

**Comment by jd2rogers2** [comment]
> i'd like to pick this ticket up! just a thought though -- could a function that maps through state to see if anything doesn't equal " " before leaving work? and then can pop up an alert? 

Go for it! Yep, pretty much! 
Idk if map will work but I think your idea is going in the right direction. And just to be clear, not a native js alert but a material ui/home cooked modal

And a little more direction here: 
- Just get it working in one of our forms to start and then in a follow up PR we can reuse in the other places
- not sure exactly how it'll work but there will essentially be some sort of listener/callback, and in that call back you should use a function that takes in the form state (object with any keys so that it can be reused for other forms) to check the form as you described
