### ISSUE TITLE
Cannot find module bcryptjs

### ISSUE THREAD

**Issue by esteban-gs** [Nonprofit-Exchange-Hub/web-app#126]
Where
---
server
on the `main` branch

What
---
App complains about missing `bcriptjs` module

May need to add the missing package: https://www.npmjs.com/package/bcryptjs

**Comment by jd2rogers2** [comment]
@esteban-gs what error did you get?
did you try `npm install`?
did you see this issue in `main` or in @dbrandt1990's branch?
danny switched to `bcryptjs` when he was having issues with `bcrypt`
danny, can you post what errors you were getting too?

**Comment by jd2rogers2** [comment]
https://javascript.plainenglish.io/node-js-bcrypt-vs-bcryptjs-benchmark-69a9e8254cc2
https://stackoverflow.com/questions/54674387/how-do-nodes-bcrypt-and-bcryptjs-libraries-differ
just some resources for context

**Comment by esteban-gs** [comment]
> @esteban-gs what error did you get? did you try `npm install`? did you see this issue in `main` or in @dbrandt1990's branch? danny switched to `bcryptjs` when he was having issues with `bcrypt` danny, can you post what errors you were getting too?

Observed on `main` at `226f6704bc1120d9afbf5323c1a1f17c87077bed`. After the new merge squash commit, issue is solved.

**Comment by dbrandt1990** [comment]
This was the error I was getting from running npm run checks. 

![error for tests](https://user-images.githubusercontent.com/54184719/148670191-74717241-1b30-4189-a536-ee30263fc1c7.png)
