### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by jonathanchuangcodes** [Nonprofit-Exchange-Hub/web-app#165]
this ticket strictly for functionality
ui fixes being handled separately

existing functionality can query assets with param type of donation, offer
need to add additional property to assets to query with param of "kind" (? naming up to you) either physical object or volunteer work
- new property in entity, create/get DTOs
  - also add fake data to the seeded data (`server/src/database/seeding/seed-data.ts`)
  - tip for updating db toggle `dropSchema` to true in `server/src/database-connection.service.ts`
- adding that param in the fetch request

**Comment by jd2rogers2** [comment]
assets were already searchable, so orgs done in [this PR](https://github.com/Nonprofit-Exchange-Hub/web-app/pull/229)
which wraps up most of what this ticket needs. volunteer post page and BE properties will be handled by another ticket
closing
