### ISSUE TITLE
BE: password reset flow

### ISSUE THREAD

**Issue by esteban-gs** [Nonprofit-Exchange-Hub/web-app#166]
Refer to #52 Bullets 2 and 4 in the [description](https://github.com/Nonprofit-Exchange-Hub/web-app/issues/52#issue-1035641141)

Some things that may help implement it

Redirect from the back-end: https://docs.nestjs.com/controllers#redirection
Sample controller for password reset: https://github.com/Nonprofit-Exchange-Hub/web-app/blob/main/server/src/auth/auth.controller.ts
Existing reset password controller method: https://github.com/Nonprofit-Exchange-Hub/web-app/blob/b7ba0f60b77a889adbbf21755ea5fcd59b1acb0e/server/src/users/users.controller.ts#L32-L43
May have to create a sendgrid account and set it up: https://docs.sendgrid.com/api-reference/mail-send/mail-send

**Comment by jd2rogers2** [comment]
closing
i'm taking over this task and will track all of my work in parent ticket https://github.com/Nonprofit-Exchange-Hub/web-app/issues/52
