### ISSUE TITLE
CallToActionSection

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#170]
Based on the most up to date designs: https://www.figma.com/file/KE2Sw6ob07agN25RmeNuFg/GiveCycle-wireframes?node-id=4076%3A12228

- large Card components with [animated button](https://nonprofitcircle.slack.com/files/U02H1MMGHDZ/F03FB3UAX1A/button_animation.mp4) 
![image](https://user-images.githubusercontent.com/16600961/171516286-adb399af-551d-4e7d-8cf8-cb91efdd93a7.png)
- separate CTACard component
- make sure to put all static text in common file

**Comment by SeaAustinCode** [comment]
Hello everyone, I'm not sure how to assign myself to this but I will be working on this.
