### ISSUE TITLE
search for nonprofits FE

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#227]
rename path/url/route and component `AssetsView` to something like `SearchResults`

can use [react-router hooks](https://v5.reactrouter.com/web/api/Hooks/uselocation) or useParams to consume url data and then conditionally make fetch request to `/orgs?searchText=blah`
also use same url data to conditionally render new card components or list component with nonprofit card components (also new np card needed)

if `non profit` is selected in search dropdown
- send get req to /organizations?name=searchInput
- when we get response takes us to nonprofit list page or something (new component?)
- this endpoint still WIP (so potentially don't do and move to new ticket)

![image](https://user-images.githubusercontent.com/16600961/171516783-11f49422-5949-4f6b-954a-6e5ee5bafb99.png)
needs to handle:

**Comment by EtoKruto** [comment]
Changes:
- `AssetsView` changed to `SearchResults` throughout
- Using location.state.category to pass state from Search component to SearchResults. TBD on filtering results
- If a nonprofit is selected, SearchResult will render a specific filtered view of all Nonprofits as cards on Grid

Opinion/Question:
- Search component currently only handles any text box input as a Search for "assets" of any kind. 
  - Option 1 [implementing in this ticket]: If we are looking to make four different Search components to be rendered for each category search, then we would need to handle each Category case and create four diff components to be rendered. 
  - Option 2 [preferred]: If not, we can just implement a single Search view (which we already have) and build in filters that would be auto-selected when we render the 'SearchResults' into view. When the 'Search All' Category is selected, the options for 'Nonprofits, Needs, Offers, Volunteer Openings' are automatically preselected. This 'everything under one roof' approach could work as long as this doesn't add to the complexity of rendering cards into view with different data.

10/24 - Review if this implementation is correct and proceeds or refactor.

**Comment by jd2rogers2** [comment]
> 10/24 - @jd2rogers2 Please review if this implementation is on the right path. Confirm to proceed or refactor.

let's keep this part simple for now. here's what i envision:
```
const [donations, setDonations] = useState();
const [orgs, setOrgs] = useState();
// ... other fetch result states

useEffect(() => {
if (searchCategory === 'donations') {
  await fetch('api/orgs?category=donations&search=${searchText}')
  setDonations(fetchResults);
  setOrgs([]); // clear prev
}
// repeated for each searchCategory (donations, requests, volunteerOpenings, nonprofits)

}, [searchText, searchCategory]);

return (
  <>
    {searchCategory === 'donations' && donations.length ? donations.map(donation => (
      <AssetCard asset={donation} />
    )) : null}
    {searchCategory === 'organizations' && orgs.length ? orgs.map(org => (
      <OrgCard org={org} />
    )) : null}
    {/** etc. **/}
  </>
);
```

**Comment by EtoKruto** [comment]
Changes:
- Updated Search Result Component for input logic and slightly cleaner UI
- Removed link when SearchIcon was pressed as this logic did not make sense
- Added dropdown for easier searching based on the category selected
- fetch API working for all orgs being pulled

Opinion/Question:
- I copied the AssersList component and created an OrgsList and VolunteerList component. These components can all live under one roof - AssetsList - there needs to be some uniformity in handling data in that component. This will allow for much less code and easier maintenance in the future if any additions are required. I've left it open-ended so that anyone can change this in future iterations.

**Comment by EtoKruto** [comment]
Issue closed
