### ISSUE TITLE
user profile page

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#236]
1. build out the user profile page
  - display all of user's info nicely to your liking
  - edit button (leave action blank, will eventually toggle this page to be a form for editing user profile)
  - let's leave the org related and assets out for now
  - put a placeholder image somewhere to later replaced with BE data
  - just got some [rough draft mocks](https://www.figma.com/file/KE2Sw6ob07agN25RmeNuFg/GiveCycle-wireframes?node-id=6442%3A42990) you can start with

**Comment by jd2rogers2** [comment]
@jalapenojames just updated the ticket as i got some mocks for you to start with (do your best but don't spend too much getting it picture perfect)

**Comment by jalapenojames** [comment]
Thank you!! Sounds good

**Comment by esteban-gs** [comment]
Sorry! this got auto-closed after I merge #280
