### ISSUE TITLE
add missing user properties

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#286]
![Image](https://user-images.githubusercontent.com/16400333/220221378-f7b50d25-8343-4e74-b324-6e0bf1c88e74.png)

our user table is missing a about_me or description property
as well as the location properties (city, state, zip)

please add
expect write, read, and update actions to work with this data

**Comment by esteban-gs** [comment]
I'm pretty sure this is done
