### ISSUE TITLE
Document Account endpoint for swagger UI

### ISSUE THREAD

**Issue by esteban-gs** [Nonprofit-Exchange-Hub/web-app#297]
**Is your feature request related to a problem? Please describe.**
We have swagger set up for the backend, most endpoints are auto-documented, but some endpoints may require a refactor to make better use of Dtos. 

**Describe the solution you'd like**
Audit the `account` endpoints and refactor the endpoints that are not automatically auto-documented by swagger

**Describe alternatives you've considered**
n.a

**Additional context**
May require also adding `UserResponseDto` to make use of [class transformer](https://docs.nestjs.com/techniques/serialization) to keep some fields out of the http responses.

**Comment by garimacha** [comment]
@esteban-gs are all the endpoints have documentation now? James mentioned that there are still some endpoints which need to get fixed? I am opening this ticket again. Let me know.

**Comment by garimacha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation for the backend API](https://trello.com/c/ThlBPQnk/22-documentation-for-the-backend-api)

**Comment by esteban-gs** [comment]
This should be done, see trello
