### ISSUE TITLE
complete swagger documentation

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#304]
we need to build on the work that esteban did, follow the same patterns to ensure that our swagger page (localhost:3001/docs) has the request and response shape documented
https://github.com/Nonprofit-Exchange-Hub/web-app/pull/299

**Comment by marvinsjsu** [comment]
first PR - https://github.com/Nonprofit-Exchange-Hub/web-app/pull/336 (`/auth`, `/assets`, `/categories`)
