### ISSUE TITLE
New styling for signed in header

### ISSUE THREAD

**Issue by esteban-gs** [Nonprofit-Exchange-Hub/web-app#333]
update the header to match the figmas in link below
when the user isn't logged in we want the header to have the links and styling like this mock

https://www.figma.com/file/K7DT5jYcLKRc9epmNrO0N7/UX---Dev-Handoff?node-id=515-3726&t=VEr5IrUb64axyP7p-0

Acceptance criteria:
- Styling resembles the mock

**Comment by marvinsjsu** [comment]
hi @paaaarv, hope all is well.  I just wanted to check-in to see if you had any questions regarding this ticket or if maybe you'd like someone else to pick this up.  Thanks in advance!

**Comment by paaaarv** [comment]
Hi @marvinsjsu - sorry for the lag! I should be able to resolve it on my own, thank you though!

**Comment by marvinsjsu** [comment]
@paaaarv, no worries and thanks for continuing to work on this.

**Comment by marvinsjsu** [comment]
Hi @paaaarv, hope all is well.  Just wanted to follow-up and see if you had any updates on this.  Thanks in advance!

**Comment by EtoKruto** [comment]
Began review and work on branch #333-signed-in-header-styling

**Comment by EtoKruto** [comment]
Submitted for PR
