### ISSUE TITLE
Finish User Sign Up Form

### ISSUE THREAD

**Issue by esteban-gs** [Nonprofit-Exchange-Hub/web-app#343]
We lost some of our validation checks on the user-signup forms during the re-design iterations.
Page 1
- First Name - required
- Last Name - required
- Email - required, client-side email validation with `Yup`
- Password- required, confirm password field can be validated to match password field
- Accept terms: validated as true before going to next page
Page 2
- City: optional, input element (not Select)
- State: optional, Select element, validated from list of states
- Zip: required
Page 3
- Interests: optional, multi-chip select
Page 4
- Profile icon: optional, file upload MUI component
- About Self: optional, Text area component

### See:
https://github.com/Nonprofit-Exchange-Hub/web-app/commit/4f732a051319f326ae696f47afae383e3a18815f#diff-b953688af7236bb02acd06305fdb9435ba02065c0c5189e5792fab963639e544

### Acceptance Criteria:
- We validate sign up fields as defined in Figma mocks. Not all fields are required. City will be an input field, not select.
- We use a file upload MUI component to properly submit a profile image to the server to the correct endoint.
- We handle client-side validation messages
- We handle http error messages

**Comment by marvinsjsu** [comment]
https://github.com/Nonprofit-Exchange-Hub/web-app/pull/363
