### ISSUE TITLE
Replace image and update copy on /signup-nonprofit

### ISSUE THREAD

**Issue by marvinsjsu** [Nonprofit-Exchange-Hub/web-app#358]
The image used in /signup-nonprofit does not match what we have in our Figma mocks.  This ticket is to replace this image with the correct asset, update the copy to include "ABOUT YOUR ORGANIZATION" text,  and adjust the layout so it matches what's provided in Figma.

Current page:

![Image](https://user-images.githubusercontent.com/2562488/254460418-1aa2c2c5-4b0e-44ca-97bb-c4dcf8e3f502.png)

Figma mock:

![Image](https://user-images.githubusercontent.com/2562488/254460446-db66bca8-1b2a-496e-a276-519b79b0aa28.png)

Figma - https://www.figma.com/file/K7DT5jYcLKRc9epmNrO0N7/UX---Dev-Handoff?type=design&node-id=1-5&mode=design&t=II3OZI8OgzhdP10A-0

**Comment by junsupark94** [comment]
@marvinsjsu Could I get access to the Figma file? I requested access to my email junsupark94@gmail.com

**Comment by marvinsjsu** [comment]
I've asked the design team for access on their channel [#design-ux-ui](https://nonprofitcircle.slack.com/archives/C01G4GR05CJ/p1690819993734719)

**Comment by junsupark94** [comment]
@EtoKruto /signup has layout but is blank for me. And /signup-nonprofit is completely blank. Could you help me with this? Text me if you can.

**Comment by junsupark94** [comment]
@marvinsjsu  /signup and /signup-nonprofit are blank on the **main** branch. I think you're looking at Dennis' branch _288 feature_ which has the routes /signup-citizen and /signup-nonprofit.

@denniswangcodes I don't think I can proceed on this ticket until you complete your pull request for these signup pages. Could you let me know when that's done?

**Comment by marvinsjsu** [comment]
@junsupark94, you're right. Sorry for the confusion here, this is my bad.  For this ticket, if you're ok with it @denniswangcodes, it can be re-assigned to you since you're already working on the signup pages?   I think @denniswangcodes tried to bring this up in our sync-up ... Again, so sorry for the confusion guys.

**Comment by denniswangcodes** [comment]
@marvinsjsu Sounds good, feel free to reassign to me since I'm already working on these signup pages and no problem at all.
@junsupark94 Correct, the signup page should no longer be needed since we implemented the modal logic to be triggered instead. The PR feature branch, once merged, should reflect expected functionality. Appreciate your awareness on this.

**Comment by marvinsjsu** [comment]
thanks @denniswangcodes @junsupark94, this is re-assigned now.
