### ISSUE TITLE
Add profile img upload on Sign Up form

### ISSUE THREAD

**Issue by marvinsjsu** [Nonprofit-Exchange-Hub/web-app#364]
In our user sign-up form, we go through multiple steps to gather profile information for creating a user account.  In this process, we allow a user to upload their profile image.  This ticket is to add this feature.

User Sign-up form -  http://localhost:3000/signup-citizen

![Image](https://user-images.githubusercontent.com/2562488/257916831-5e6bb01f-fc70-413f-bee5-746006c59507.png)

**Comment by esteban-gs** [comment]
Blocked by: https://github.com/Nonprofit-Exchange-Hub/web-app/pull/363, #343
