### ISSUE TITLE
Display error message for State select field on Sign Up form

### ISSUE THREAD

**Issue by marvinsjsu** [Nonprofit-Exchange-Hub/web-app#365]
In the user sign up form, we ask for the user to select the state they live in.  This ticket is an enhancement to how this select field currently works.  Other input fields (city and zip code) displayed "Required." message under the field when user un-focuses (`onBlur`) from it and there is a validation error.  It would be nice to follow this format (to display "Required.") if the user has tabbed out of the field before selecting a state.

User Sign Up form - http://localhost:3000/signup-citizen

![Image](https://user-images.githubusercontent.com/2562488/257919354-7132e73d-acce-43de-ae30-09e3dabeb6a2.png)

**Comment by esteban-gs** [comment]
Blocked by https://github.com/Nonprofit-Exchange-Hub/web-app/issues/343 #343
