### ISSUE TITLE
password reset flow

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#52]
these are ordered in the chronological flow but can be handled by dev in any order

1. (FE portion)
from login page, we have a `forgot password` link, this should take user to a new page
this new page should look exactly like the login page except only have 1 email input
on submit, sends request to BE with this email. endpoint to be created in step 2
(maybe step 5 can be handled here but maybe not)

2. (BE portion)
new endpoint (maybe just in app module?) `/api/reset_password`
no auth necessary to hit this endpoint
endpoint receives email via post body
check email is in db, respond with 500? or some error code that doesn't disclose user exists
send email to given email address
email body should include link back to NEH site with jwt signed by us with a secret that is saved in local var
jwt should include user's email as data
also says something like (if you didn't request this don't worry blah)
more resources here https://github.com/Nonprofit-Exchange-Hub/web-app/issues/166

3. (FE portion)
`/set_new_password`
again, similar to login page but only with password input
on submit passes new password and token back to BE

4. (BE portion)
`/api/users/set_new_password`
receives jwt and new password
parse jwt using same secret from step 2
get's user by email
updates user's email, use bcrypt
more resources here https://github.com/Nonprofit-Exchange-Hub/web-app/issues/166

5. (FE portion)
reset password view displays correct error messages to user
`/api/reset_password` should not disclose user exists, and throw error message and code accordingly
ui should display message

resources:
[mocks for login page](https://www.figma.com/file/fYkreARKdHsMh8iPSh7dti/GC-prototype-v1?node-id=0%3A648)

**Comment by kevhines** [comment]
Haven't made a ton of progress here. Step 1 completed, Step 2 started.
Step 2 checks if email is in db, but currently doesn't send an email (which will send a link to a reset password)
