### ISSUE TITLE
create Assets resource

### ISSUE THREAD

**Issue by jd2rogers2** [Nonprofit-Exchange-Hub/web-app#53]
work for this ticket should result in:
an assets module including entity, service, controller with basic CRUD endpoints
using curl/httpie/postman/etc you should be able to get appropriate success and error responses
set up any relationships that are listed in https://drive.google.com/file/d/1GR0hJ7P9tDepDUW0tjpOrC5d8iE-Elx1/view?usp=sharing

reference https://drive.google.com/file/d/1GR0hJ7P9tDepDUW0tjpOrC5d8iE-Elx1/view?usp=sharing for data model attributes
also can follow similar pattern of User resource/module

later steps include: (so don't do any of these just yet)
adding auth checks to any of these endpoints that need it

**Comment by Sunset05** [comment]
completed PR
